In [38]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('A2data.csv')

a) 

In [16]:
df.groupby('Ratios').agg('mean')

X1        X2        X3
Ratios                              
B       1.944737  2.670526  1.859474
G       1.795500  2.858000  2.092500

b) Covariance matrix

In [19]:
df.loc[:, ['X1', 'X2', 'X3']].cov()

X1        X2        X3
X1  0.019689  0.007225 -0.001907
X2  0.007225  0.060770  0.017928
X3 -0.001907  0.017928  0.034183

c)

In [21]:
cov_mat = df.loc[:, ['X1', 'X2', 'X3']].cov().to_numpy()

In [32]:
mean_b = df.groupby('Ratios').agg('mean').loc['B',:].to_numpy()
mean_g = df.groupby('Ratios').agg('mean').loc['G',:].to_numpy()

In [74]:
print(f'mean_b: {mean_b}')
print(f'mean_g: {mean_g}')
print(f'cov_mat: \n {cov_mat}')

mean_b: [1.94473684 2.67052632 1.85947368]
mean_g: [1.7955 2.858  2.0925]
cov_mat: 
 [[ 0.0196888   0.00722544 -0.00190715]
 [ 0.00722544  0.06077018  0.01792807]
 [-0.00190715  0.01792807  0.03418313]]


In [41]:
weights = np.matmul(np.linalg.inv(cov_mat), np.transpose(mean_g - mean_b))

In [42]:
weights

array([-8.03090042,  2.55644027,  5.02815625])

In [44]:
normalized_weights = weights / sum(weights)

In [46]:
normalized_weights

array([ 17.9942422 ,  -5.72802588, -11.26621632])

d)

In [49]:
def calc_scores(x, w):
    return w.dot(x.values)

In [55]:
df['scores'] = df[['X1', 'X2', 'X3']].apply(lambda x: calc_scores(x, normalized_weights), axis=1)

In [65]:
td = df[['Ratios', 'scores']].sort_values('scores').reset_index().drop('index', axis=1)
td

Ratios     scores
0       G -10.485017
1       G -10.289887
2       G -10.138868
3       G -10.099632
4       G  -9.829942
5       G  -9.678983
6       G  -8.864397
7       G  -8.447293
8       G  -8.102221
9       G  -8.055823
10      G  -7.299847
11      G  -7.187440
12      G  -6.908124
13      G  -6.868888
14      G  -6.325005
15      G  -5.664162
16      B  -5.017307
17      G  -5.003005
18      G  -4.806799
19      B  -4.791612
20      G  -4.468378
21      G  -4.208166
22      B  -4.197598
23      B  -2.654063
24      B  -2.278544
25      B  -2.032398
26      B  -1.356563
27      B  -1.258890
28      B  -0.900021
29      B  -0.859571
30      B  -0.720449
31      B  -0.596087
32      B  -0.404186
33      B  -0.241271
34      B   0.050963
35      B   0.058496
36      B   0.192353
37      B   1.607019
38      B   1.611522

In [68]:
td[td['Ratios'] == 'G'].index.max()

21

In [71]:
td[td['Ratios'] == 'B'].index.min()

16

In [73]:
(td.iloc[22]['scores'] + td.iloc[15]['scores'])/2

-4.930879593035387