In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
df = pd.read_csv('A2Q6Data.csv')

In [3]:
df[['WMT', 'IBM', 'SO', 'LMT']].mean()

WMT    0.011100
IBM    0.004148
SO     0.011076
LMT    0.008867
dtype: float64

In [4]:
mean_return = df[['WMT', 'IBM', 'SO', 'LMT']].mean().to_numpy()

In [5]:
mean_return

array([0.01109954, 0.00414849, 0.01107632, 0.00886721])

In [6]:
df[['WMT', 'IBM', 'SO', 'LMT']].cov()

WMT       IBM        SO       LMT
WMT  0.003333  0.000664  0.001005  0.000738
IBM  0.000664  0.005158  0.001922  0.003172
SO   0.001005  0.001922  0.003312  0.001525
LMT  0.000738  0.003172  0.001525  0.004289

In [7]:
cov = df[['WMT', 'IBM', 'SO', 'LMT']].cov().to_numpy()

In [8]:
cov

array([[0.00333268, 0.00066385, 0.00100533, 0.00073766],
       [0.00066385, 0.00515828, 0.00192171, 0.00317215],
       [0.00100533, 0.00192171, 0.00331232, 0.001525  ],
       [0.00073766, 0.00317215, 0.001525  , 0.00428916]])

In [9]:
def lagrangian_multiplier_solver(x_bar, cov_matrix, target_return):
    n = len(x_bar) # number of assets
    A = np.hstack((np.vstack((cov_matrix, x_bar, np.ones(n))), 
                   np.vstack((x_bar.reshape(n,1), np.zeros((2,1)))),
                   np.vstack((np.ones((n,1)), np.zeros((2, 1))))))
    b =  np.vstack((np.zeros((n,1)), [[target_return]], [[1]]))
    return np.linalg.inv(A).dot(b)

In [10]:
params = lagrangian_multiplier_solver(mean_return, cov, 0.05)

In [11]:
params

array([[ 1.04911292],
       [-6.53214541],
       [ 3.60664752],
       [ 2.87638496],
       [-3.14349218],
       [ 0.02998366]])

In [15]:
weights = params[:4]

In [16]:
weights

array([[ 1.04911292],
       [-6.53214541],
       [ 3.60664752],
       [ 2.87638496]])

In [13]:
weights.T.dot(mean_return)

array([0.05])

In [14]:
math.sqrt(weights.T.dot(cov).dot(weights))

0.35663840541382297